src/objects/Visual_Process__c.object
<CustomObject>
    <label>Visual Process</label>
    <nameField>
        <label>Visual Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisualProcessComponent__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>VisualProcessComponent__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visual Process Component Type</label>
        <referenceTo>VisualProcessComponentType__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visual_Process__c</fullName>
        <label>Visual Process</label>
        <referenceTo>Visual_Process__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visual Process Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Process Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VisualProcessComponentType__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Visual Process Component Type</label>
    <nameField>
        <label>Visual Process Component Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Process Component Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisualProcessComponentsUpdateController.cls
public class VisualProcessComponentsUpdateController{
    
    @AuraEnabled
    public static String addNewComponent(String type, String name, String label, String parent, Decimal position, String visualProcessId){
        try{
            
            VisualProcessComponentType__c cmpType = [SELECT Id FROM VisualProcessComponentType__c WHERE Name = :type];
            
            VisualProcessComponent__c cmp = new VisualProcessComponent__c(
            	Name = name,
                Label__c = label,
                Visual_Process__c = visualProcessId,
                Type__c = cmpType.Id,
                Parent__c = parent,
                Position__c = position 
            );
            
            insert cmp;
            
            return cmp.Id;
        } catch(Exception ex){
            throw new AuraHandledException('Exception: ' + ex.getMessage() + ' - ' + ex.getStackTraceString());
        }
    } 
    
    @AuraEnabled
    public static Boolean removeStep(String sfId){
        try{
            VisualProcessComponent__c cmp = new VisualProcessComponent__c(Id = sfId);
            
            delete cmp;
            
            return true; 
        } catch(Exception ex){
            throw new AuraHandledException('Exception: ' + ex.getMessage() + ' - ' + ex.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static Boolean editStepName(String sfId, String newName){
        try{
            VisualProcessComponent__c cmp = new VisualProcessComponent__c(Id = sfId, Name = newName);
            
            update cmp;
            
            return true;
        } catch(Exception ex){
            throw new AuraHandledException('Exception: ' + ex.getMessage() + ' - ' + ex.getStackTraceString());
        }
    }
        
        
        
}