src/objects/Visual_Process__c.object
<CustomObject>
    <label>Visual Process</label>
    <nameField>
        <label>Visual Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisualProcessComponent__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>VisualProcessComponent__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visual Process Component Type</label>
        <referenceTo>VisualProcessComponentType__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visual_Process__c</fullName>
        <label>Visual Process</label>
        <referenceTo>Visual_Process__c</referenceTo>
        <relationshipLabel>Visual Process Components</relationshipLabel>
        <relationshipName>Visual_Process_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visual Process Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Process Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VisualProcessComponentType__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Visual Process Component Type</label>
    <nameField>
        <label>Visual Process Component Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visual Process Component Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisualProcessGetData.cls
public class VisualProcessGetData {

    @AuraEnabled
    public static List<Map<String, Object>> getFlow(String visualProcessId){
        
        /*
            [
                {
                    "type" : "step"
                    "name" : "Name Step 1"
                    "childs" : [
                        {
                            "type":"number",
                            "name":"NameNumber1",
                            "label":"Label Number 1"
                        },
                        {
                            "type":"text",
                            "name":"Name Text 1",
                            "label":"Label Text 1"
                        },
                        {
                            "type":"text",
                            "name":"Name Text 2",
                            "label":"Label Text 2"
                        }
                    ]
                },
                {
                    "type" : "step"
                    "name" : "Name Step 2"
                },
                {
                    "type" : "step"
                    "name" : "Name Step 3"
                },
                
            ]

        */
        
        try{
            List<Map<String, Object>> retFlow = new List<Map<String, Object>>(); 
            Map<String, Object> c; 


            
            List<VisualProcessComponent__c> cmps = [SELECT Id, Name,
                                                        Label__c,
                                                        Parent__c,
                                                        Type__r.Name
                                                    FROM VisualProcessComponent__c
                                                    WHERE Visual_Process__c = :visualProcessId];

            if(cmps.size() == 0)
                return null;

            for(VisualProcessComponent__c cmp : cmps){
                if(cmp.Type__r.Name == 'step'){
                    c = new Map<String, Object>();
                    c.put('sfId', cmp.Id);
                    c.put('name', cmp.Name);
                    c.put('label', cmp.Label__c);
                    c.put('type', 'step');
                    c.put('childs', new List<Map<String, Object>>());
                    
                    retFlow.add(c);
                }
            }
    
            return retFlow;

        } catch(Exception ex){
            throw new AuraHandledException('Exception: ' + ex.getMessage() + ' - ' + ex.getStackTraceString());
        }
    }
}